"""Unified in-process scheduler for obsidian-rag cron-style jobs.

Replaces ~24 individual launchd plists with a single long-running
`BackgroundScheduler` (APScheduler 3.x). Each job runs the CLI command
as a subprocess with a per-job timeout (default 25min).

Activation: ``RAG_USE_SCHEDULER=1`` — without it the legacy individual
plists are still installed by ``rag setup`` (no behaviour change).

Config file: ``~/.config/obsidian-rag/scheduler.yaml``
  Generated by ``_write_default_scheduler_yaml()`` on first run.

State table: ``rag_scheduler_runs`` in telemetry.db
  id, ts_start, ts_end, job_name, exit_code, duration_s, error_msg

CLI:
  rag scheduler          — start the daemon (blocks; KeepAlive via plist)
  rag scheduler status   — list jobs with last_run / next_run / last_status
"""

from __future__ import annotations

import logging
import os
import subprocess
import threading
import time
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

# ── constants ────────────────────────────────────────────────────────────────

_CONFIG_DIR = Path.home() / ".config" / "obsidian-rag"
_SCHEDULER_YAML = _CONFIG_DIR / "scheduler.yaml"
_DEFAULT_TIMEOUT_MINUTES = 25
_DEFAULT_ENV_PATH = (
    "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:"
    + str(Path.home() / ".local" / "bin")
)

# Jobs that move into the scheduler (cron-style, NOT KeepAlive).
# These are extracted from the actual plist schedules.
_DEFAULT_JOBS: dict[str, dict[str, Any]] = {
    "morning": {
        "cron": "0 7 * * 1-5",
        "command": "rag morning",
        "enabled": True,
        "env": {"RAG_EXPLORE": "1"},
    },
    "today": {
        "cron": "0 22 * * 1-5",
        "command": "rag today",
        "enabled": True,
        "env": {"RAG_EXPLORE": "1"},
    },
    "digest": {
        "cron": "0 22 * * 0",
        "command": "rag digest",
        "enabled": True,
    },
    "anticipate": {
        "interval_minutes": 10,
        "command": "rag anticipate run",
        "enabled": True,
    },
    "ingest-whatsapp": {
        "interval_minutes": 15,
        "command": "rag index --source whatsapp",
        "enabled": True,
        "env": {"OLLAMA_KEEP_ALIVE": "-1"},
        "run_at_start": True,
    },
    "ingest-gmail": {
        "interval_minutes": 60,
        "command": "rag index --source gmail",
        "enabled": True,
        "env": {"OLLAMA_KEEP_ALIVE": "-1"},
        "run_at_start": True,
    },
    "ingest-calendar": {
        "interval_minutes": 60,
        "command": "rag index --source calendar",
        "enabled": True,
        "env": {"OLLAMA_KEEP_ALIVE": "-1"},
        "run_at_start": True,
    },
    "ingest-reminders": {
        "interval_minutes": 60,
        "command": "rag index --source reminders",
        "enabled": True,
        "env": {"OLLAMA_KEEP_ALIVE": "-1"},
        "run_at_start": True,
    },
    "ingest-drive": {
        "interval_minutes": 60,
        "command": "rag index --source drive",
        "enabled": True,
        "env": {"OLLAMA_KEEP_ALIVE": "-1"},
        "run_at_start": True,
    },
    "wa-tasks": {
        "interval_minutes": 30,
        "command": "rag wa-tasks",
        "enabled": True,
    },
    "reminder-wa-push": {
        "interval_minutes": 5,
        "command": "rag remind-wa",
        "enabled": True,
    },
    "wa-scheduled-send": {
        "interval_minutes": 5,
        "command": "rag wa-scheduled-send",
        "enabled": True,
    },
    "implicit-feedback": {
        # 03:25 daily — runs before online-tune (03:30)
        "cron": "25 3 * * *",
        "command": (
            "rag feedback infer-implicit --json && "
            "rag feedback detect-requery --json && "
            "rag feedback classify-sessions --json"
        ),
        "enabled": True,
        "shell": True,
    },
    "online-tune": {
        # 4× daily: 03:30, 09:30, 15:30, 21:30
        "cron": "30 3,9,15,21 * * *",
        "command": "rag tune --online --days 14 --apply --yes",
        "enabled": True,
        "timeout_minutes": 50,
        "env": {"RAG_EVAL_GATE_TIMEOUT_S": "2400"},
        "nice": 10,
    },
    "calibrate": {
        "cron": "30 4 * * *",
        "command": "rag calibrate --since 90 --as-json",
        "enabled": True,
        "env": {"RAG_SCORE_CALIBRATION": "0"},
    },
    "auto-harvest": {
        "cron": "0 3 * * *",
        "command": "rag feedback auto-harvest --since 1 --limit 50 --json",
        "enabled": True,
    },
    "active-learning-nudge": {
        # Mondays 10:00
        "cron": "0 10 * * 1",
        "command": "rag active-learning nudge --json",
        "enabled": True,
    },
    "maintenance": {
        "cron": "0 4 * * *",
        "command": "rag maintenance",
        "enabled": True,
    },
    "consolidate": {
        # Mondays 06:00
        "cron": "0 6 * * 1",
        "command": "rag consolidate --apply",
        "enabled": True,
        "env": {"OLLAMA_KEEP_ALIVE": "-1"},
    },
    "vault-cleanup": {
        "cron": "0 2 * * *",
        "command": "rag vault-cleanup",
        "enabled": True,
    },
    "archive": {
        # 1st of month 23:00
        "cron": "0 23 1 * *",
        "command": "rag archive --apply --notify --report",
        "enabled": True,
    },
    "emergent": {
        # Fridays 10:00
        "cron": "0 10 * * 5",
        "command": "rag emergent",
        "enabled": True,
    },
    "patterns": {
        # Sundays 20:00
        "cron": "0 20 * * 0",
        "command": "rag patterns",
        "enabled": True,
    },
    "whisper-vocab": {
        "cron": "15 3 * * *",
        "command": "rag whisper vocab refresh",
        "enabled": True,
    },
    "lgbm-train": {
        # Sundays 02:30
        "cron": "30 2 * * 0",
        "command": "rag tune-lambdarank --apply",
        "enabled": True,
        "nice": 10,
    },
    "synth-refresh": {
        # Saturdays 22:00
        "cron": "0 22 * * 6",
        "command": (
            "rag synth-queries generate --apply --json && "
            "rag synth-queries mine-negatives --apply --json"
        ),
        "enabled": True,
        "shell": True,
        "nice": 10,
    },
    "routing-rules": {
        "cron": "30 3 * * *",
        "command": (
            "rag routing extract-rules --auto-promote "
            "--min-count 5 --min-ratio 0.90 --days 60"
        ),
        "enabled": True,
    },
    "wake-up": {
        "cron": "0 4 * * *",
        "command": "rag wake-up",
        "enabled": True,
        "env": {"OLLAMA_KEEP_ALIVE": "-1"},
    },
}


def _write_default_scheduler_yaml() -> None:
    """Write the default scheduler.yaml if it doesn't exist."""
    _CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    if _SCHEDULER_YAML.exists():
        return
    doc = {"jobs": _DEFAULT_JOBS}
    with open(_SCHEDULER_YAML, "w", encoding="utf-8") as fh:
        yaml.dump(doc, fh, default_flow_style=False, allow_unicode=True, sort_keys=True)
    logger.info("wrote default scheduler config to %s", _SCHEDULER_YAML)


def load_scheduler_config(config_path: Path | None = None) -> dict[str, dict[str, Any]]:
    """Load and validate the scheduler YAML.  Returns {job_name: job_dict}."""
    path = config_path or _SCHEDULER_YAML
    if not path.exists():
        return dict(_DEFAULT_JOBS)
    with open(path, encoding="utf-8") as fh:
        raw = yaml.safe_load(fh) or {}
    jobs = raw.get("jobs", {})
    validated: dict[str, dict[str, Any]] = {}
    for name, cfg in jobs.items():
        if not isinstance(cfg, dict):
            logger.warning("scheduler: job %r has invalid config, skipping", name)
            continue
        if "command" not in cfg:
            logger.warning("scheduler: job %r missing 'command', skipping", name)
            continue
        if not cfg.get("enabled", True):
            continue
        if "cron" not in cfg and "interval_minutes" not in cfg:
            logger.warning(
                "scheduler: job %r has neither 'cron' nor 'interval_minutes', skipping", name
            )
            continue
        validated[name] = cfg
    return validated


# ── telemetry ────────────────────────────────────────────────────────────────

_SCHEDULER_RUNS_DDL = (
    "CREATE TABLE IF NOT EXISTS rag_scheduler_runs ("
    " id INTEGER PRIMARY KEY AUTOINCREMENT,"
    " ts_start TEXT NOT NULL,"
    " ts_end TEXT,"
    " job_name TEXT NOT NULL,"
    " exit_code INTEGER,"
    " duration_s REAL,"
    " error_msg TEXT"
    ")"
)
_SCHEDULER_RUNS_IDX = (
    "CREATE INDEX IF NOT EXISTS ix_rag_scheduler_runs_ts "
    "ON rag_scheduler_runs(ts_start)",
    "CREATE INDEX IF NOT EXISTS ix_rag_scheduler_runs_job "
    "ON rag_scheduler_runs(job_name, ts_start)",
)


def _ensure_scheduler_table(db_path: Path) -> None:
    import sqlite3

    db_path.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(db_path / "telemetry.db"))
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute(_SCHEDULER_RUNS_DDL)
    for idx in _SCHEDULER_RUNS_IDX:
        conn.execute(idx)
    conn.commit()
    conn.close()


def _log_run(
    db_path: Path,
    job_name: str,
    ts_start: str,
    ts_end: str,
    exit_code: int,
    duration_s: float,
    error_msg: str | None,
) -> None:
    import sqlite3
    from datetime import datetime

    try:
        conn = sqlite3.connect(str(db_path / "telemetry.db"), timeout=10)
        conn.execute(
            "INSERT INTO rag_scheduler_runs"
            " (ts_start, ts_end, job_name, exit_code, duration_s, error_msg)"
            " VALUES (?,?,?,?,?,?)",
            (ts_start, ts_end, job_name, exit_code, duration_s, error_msg),
        )
        conn.commit()
        conn.close()
    except Exception as exc:  # pragma: no cover
        logger.warning("scheduler: failed to log run for %r: %s", job_name, exc)


def read_last_runs(db_path: Path, n: int = 1) -> list[dict]:
    """Return the most recent N runs per job from rag_scheduler_runs."""
    import sqlite3

    telemetry = db_path / "telemetry.db"
    if not telemetry.exists():
        return []
    try:
        conn = sqlite3.connect(str(telemetry), timeout=5)
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM rag_scheduler_runs ORDER BY ts_start DESC LIMIT ?",
            (n * 100,),
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


# ── job runner ───────────────────────────────────────────────────────────────

def _run_job(job_name: str, job_cfg: dict[str, Any], db_path: Path) -> None:
    """Execute a single scheduler job as a subprocess, log the result."""
    from datetime import datetime, timezone

    command = job_cfg["command"]
    timeout_s = job_cfg.get("timeout_minutes", _DEFAULT_TIMEOUT_MINUTES) * 60
    use_shell = job_cfg.get("shell", False)
    extra_env = job_cfg.get("env", {})
    nice_val = job_cfg.get("nice")

    env = {**os.environ, "PATH": _DEFAULT_ENV_PATH, "NO_COLOR": "1", "TERM": "dumb"}
    env.update(extra_env)

    ts_start = datetime.now(timezone.utc).isoformat()
    t0 = time.monotonic()
    exit_code = -1
    error_msg = None

    logger.info("scheduler: starting job %r: %s", job_name, command)

    try:
        cmd: str | list[str]
        if use_shell:
            cmd = command
        else:
            import shlex
            cmd = shlex.split(command)

        kwargs: dict[str, Any] = {
            "env": env,
            "shell": use_shell,
            "timeout": timeout_s,
        }
        if nice_val is not None and hasattr(os, "nice"):
            # preexec_fn sets niceness in the child process
            _nice = nice_val
            kwargs["preexec_fn"] = lambda: os.nice(_nice)

        result = subprocess.run(cmd, **kwargs)
        exit_code = result.returncode
        if exit_code != 0:
            error_msg = f"exit_code={exit_code}"
            logger.warning("scheduler: job %r exited %d", job_name, exit_code)
        else:
            logger.info("scheduler: job %r finished OK", job_name)
    except subprocess.TimeoutExpired:
        exit_code = -2
        error_msg = f"timeout after {timeout_s}s"
        logger.error("scheduler: job %r timed out after %ds", job_name, timeout_s)
    except Exception as exc:
        exit_code = -3
        error_msg = str(exc)
        logger.error("scheduler: job %r raised: %s", job_name, exc)

    duration_s = time.monotonic() - t0
    ts_end = datetime.now(timezone.utc).isoformat()
    _log_run(db_path, job_name, ts_start, ts_end, exit_code, duration_s, error_msg)


# ── scheduler lifecycle ───────────────────────────────────────────────────────

_scheduler_instance: Any | None = None
_scheduler_lock = threading.Lock()


def build_scheduler(jobs: dict[str, dict[str, Any]], db_path: Path) -> Any:
    """Instantiate an APScheduler BackgroundScheduler with all enabled jobs."""
    from apscheduler.schedulers.background import BackgroundScheduler
    from apscheduler.triggers.cron import CronTrigger
    from apscheduler.triggers.interval import IntervalTrigger

    scheduler = BackgroundScheduler(timezone="America/Argentina/Buenos_Aires")

    for job_name, job_cfg in jobs.items():
        if "cron" in job_cfg:
            trigger = CronTrigger.from_crontab(
                job_cfg["cron"], timezone="America/Argentina/Buenos_Aires"
            )
        else:
            interval_min = int(job_cfg["interval_minutes"])
            trigger = IntervalTrigger(minutes=interval_min)

        scheduler.add_job(
            _run_job,
            trigger=trigger,
            args=(job_name, job_cfg, db_path),
            id=job_name,
            name=job_name,
            max_instances=1,
            coalesce=True,
            misfire_grace_time=300,
            replace_existing=True,
        )
        logger.info("scheduler: registered job %r", job_name)

    return scheduler


def start_scheduler(config_path: Path | None = None, db_path: Path | None = None) -> None:
    """Start the scheduler daemon (blocks until SIGTERM/KeyboardInterrupt)."""
    import signal

    from apscheduler.schedulers.background import BackgroundScheduler

    # Import here to avoid circular imports at module level
    from rag import DB_PATH as _DEFAULT_DB_PATH

    resolved_db = db_path or _DEFAULT_DB_PATH
    _write_default_scheduler_yaml()
    jobs = load_scheduler_config(config_path)

    _ensure_scheduler_table(resolved_db)

    scheduler = build_scheduler(jobs, resolved_db)

    # Fire run_at_start jobs immediately in background threads
    for job_name, job_cfg in jobs.items():
        if job_cfg.get("run_at_start"):
            t = threading.Thread(
                target=_run_job, args=(job_name, job_cfg, resolved_db), daemon=True
            )
            t.start()

    scheduler.start()
    logger.info("scheduler: started with %d jobs", len(jobs))

    stop_event = threading.Event()

    def _handle_stop(signum, frame):
        logger.info("scheduler: received signal %d, shutting down", signum)
        stop_event.set()

    signal.signal(signal.SIGTERM, _handle_stop)
    signal.signal(signal.SIGINT, _handle_stop)

    try:
        stop_event.wait()
    finally:
        scheduler.shutdown(wait=False)
        logger.info("scheduler: stopped")


def get_scheduler_status(db_path: Path | None = None) -> list[dict]:
    """Return status of each known job: name, last_run, exit_code, next_run."""
    from rag import DB_PATH as _DEFAULT_DB_PATH

    resolved_db = db_path or _DEFAULT_DB_PATH
    rows = read_last_runs(resolved_db, n=1)
    # Index by job_name, keep only the most recent
    by_job: dict[str, dict] = {}
    for row in rows:
        name = row["job_name"]
        if name not in by_job:
            by_job[name] = row

    jobs = load_scheduler_config()
    result = []
    for job_name in jobs:
        last = by_job.get(job_name, {})
        result.append(
            {
                "job_name": job_name,
                "enabled": True,
                "last_run": last.get("ts_start"),
                "last_exit_code": last.get("exit_code"),
                "last_duration_s": last.get("duration_s"),
                "last_error": last.get("error_msg"),
            }
        )
    return result


# ── plist factory (registered in _services_spec) ──────────────────────────────

def scheduler_plist(rag_bin: str) -> str:
    """Generate the launchd plist for the unified scheduler daemon."""
    home = Path.home()
    log_dir = home / ".local/share/obsidian-rag"
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.fer.obsidian-rag-scheduler</string>
  <key>ProgramArguments</key>
  <array>
    <string>{rag_bin}</string>
    <string>scheduler</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key><string>{home}</string>
    <key>PATH</key><string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:{home}/.local/bin</string>
    <key>NO_COLOR</key><string>1</string>
    <key>TERM</key><string>dumb</string>
    <key>RAG_USE_SCHEDULER</key><string>1</string>
  </dict>
  <key>KeepAlive</key><true/>
  <key>RunAtLoad</key><true/>
  <key>StandardOutPath</key><string>{log_dir}/scheduler.log</string>
  <key>StandardErrorPath</key><string>{log_dir}/scheduler.error.log</string>
</dict>
</plist>
"""
