"""Apple Health ETL — parse `export.xml` from iCloud Drive and persist
daily aggregates to `rag_apple_health_daily` for the home dashboard.

The `export.xml` is generated by Apple Health → Share → "Export Health
Data" on iPhone. Lands in iCloud Drive at
`~/Library/Mobile Documents/com~apple~CloudDocs/Health/export.xml`
(override path via env `OBSIDIAN_RAG_HEALTH_EXPORT`). File is ~1.9 GB —
we stream-parse with `xml.etree.ElementTree.iterparse` clearing each
element after processing (SAX-like, constant memory).

Pipeline per `import_export_xml(days=N)`:
  1. iterparse over `<Record>` + `<ActivitySummary>` + `<Workout>`.
  2. For Records: aggregate per local-date bucket. SUM for accumulators
     (steps, distance, kcal, flights, exercise time). AVG for sensors
     (heart rate, HRV, resting HR).
  3. For ActivitySummary: pre-aggregated kcal/exercise/stand goals.
  4. For Workout: count per day + types_seen list.
  5. UPSERT into `rag_apple_health_daily`.

Idempotent: incremental imports update existing rows. Re-running over
the same file produces the same final state (no duplicate accumulation
because we aggregate per pass — the final aggregate replaces, not adds).

Silent-fail: if the export file doesn't exist or is malformed, the
function returns `{"imported": 0, "skipped_reason": "..."}`. The home
panel handles this by showing a placeholder ("sin export reciente · ...").
"""
from __future__ import annotations

import logging
import os
import time
import xml.etree.ElementTree as ET
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


# ── Paths + constants ─────────────────────────────────────────────────────

_DEFAULT_EXPORT = (
    Path.home() / "Library/Mobile Documents/com~apple~CloudDocs/Health/export.xml"
)


def _export_path() -> Path:
    """Resolve the path to the Apple Health export.xml.

    Override via env `OBSIDIAN_RAG_HEALTH_EXPORT=/abs/path/to/export.xml`
    for testing or if the user keeps the file outside iCloud Drive.
    """
    override = os.environ.get("OBSIDIAN_RAG_HEALTH_EXPORT")
    return Path(override) if override else _DEFAULT_EXPORT


# Records we care about. Anything else is ignored at parse time to save
# CPU. Lists capture: (record_type, agg_kind, target_field).
#
# agg_kind:
#   "sum"  → accumulate numeric value per date.
#   "avg"  → list of values, finalize as mean.
#   "max"  → latest value per date.
_RECORD_FIELDS: dict[str, tuple[str, str]] = {
    "HKQuantityTypeIdentifierStepCount":             ("sum", "steps"),
    "HKQuantityTypeIdentifierDistanceWalkingRunning":("sum", "distance_km"),
    "HKQuantityTypeIdentifierFlightsClimbed":        ("sum", "flights_climbed"),
    "HKQuantityTypeIdentifierActiveEnergyBurned":    ("sum", "active_kcal_records"),
    "HKQuantityTypeIdentifierAppleExerciseTime":     ("sum", "exercise_min_records"),
    "HKQuantityTypeIdentifierHeartRate":             ("avg", "hr_avg"),
    "HKQuantityTypeIdentifierRestingHeartRate":      ("avg", "resting_hr"),
    "HKQuantityTypeIdentifierHeartRateVariabilitySDNN": ("avg", "hrv_sdnn"),
    "HKQuantityTypeIdentifierOxygenSaturation":      ("avg", "spo2_avg"),
    "HKQuantityTypeIdentifierRespiratoryRate":       ("avg", "resp_rate"),
    "HKQuantityTypeIdentifierVO2Max":                ("max", "vo2_max"),
    "HKQuantityTypeIdentifierBodyMass":              ("max", "body_mass_kg"),
}

# Distance comes in km but some sources emit miles — convert at parse time.
_KM_PER_MILE = 1.609344


def _ensure_table() -> None:
    """Create `rag_apple_health_daily` if missing. Called lazily on first
    import. DDL aligned with the rest of telemetry (date PK + updated_at
    REAL epoch + flexible nullable metric columns).
    """
    from rag import _ragvec_state_conn  # noqa: PLC0415

    with _ragvec_state_conn() as conn:
        conn.execute(
            "CREATE TABLE IF NOT EXISTS rag_apple_health_daily ("
            " date TEXT PRIMARY KEY,"
            " steps INTEGER,"
            " distance_km REAL,"
            " flights_climbed INTEGER,"
            " active_kcal REAL,"
            " active_kcal_goal REAL,"
            " exercise_min INTEGER,"
            " exercise_goal INTEGER,"
            " stand_hours INTEGER,"
            " stand_goal INTEGER,"
            " resting_hr REAL,"
            " hr_avg REAL,"
            " hrv_sdnn REAL,"
            " spo2_avg REAL,"
            " resp_rate REAL,"
            " vo2_max REAL,"
            " body_mass_kg REAL,"
            " n_workouts INTEGER,"
            " workout_types TEXT,"
            " updated_at REAL NOT NULL"
            ")"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS ix_rag_apple_health_daily_updated "
            "ON rag_apple_health_daily(updated_at DESC)"
        )


def _parse_date(s: str | None) -> Optional[str]:
    """Apple Health dates look like `2026-05-13 08:05:21 -0300`. We
    want the LOCAL-date prefix (`2026-05-13`). The tz offset is the
    user's local at capture time, which is what we want — a "step at
    9pm" stays on the same calendar day in their local frame.
    """
    if not s or len(s) < 10:
        return None
    return s[:10]  # YYYY-MM-DD


def _bucket() -> dict:
    """Per-date aggregate skeleton. None means "no signal yet"."""
    return {
        "steps": 0,
        "distance_km": 0.0,
        "flights_climbed": 0,
        "active_kcal_records": 0.0,
        "exercise_min_records": 0,
        # avg fields: list of (value, weight=1) — mean computed at finalize.
        "hr_avg": [],
        "resting_hr": [],
        "hrv_sdnn": [],
        "spo2_avg": [],
        "resp_rate": [],
        # max fields: take latest single value seen (last wins).
        "vo2_max": None,
        "body_mass_kg": None,
        # ActivitySummary overrides (when present, they're authoritative).
        "active_kcal_summary": None,
        "active_kcal_goal": None,
        "exercise_min_summary": None,
        "exercise_goal": None,
        "stand_hours": None,
        "stand_goal": None,
        # Workouts.
        "n_workouts": 0,
        "workout_types": set(),
    }


def import_export_xml(
    days: int = 30,
    export_path: Optional[Path] = None,
) -> dict:
    """Stream-parse export.xml and persist daily aggregates for the last
    `days` days. Older records are skipped without ever touching them
    (cheap — startDate is the first attribute we inspect).

    Args:
      days: How many days back to ingest. 30 covers the home dashboard
        sparklines (14d) with buffer. Set higher for backfill.
      export_path: Override path (testing). Defaults to env or iCloud.

    Returns:
      `{imported: N, days_seen: [...], elapsed_s, skipped_reason?}`.
    """
    path = export_path or _export_path()
    if not path.exists():
        return {"imported": 0, "skipped_reason": f"missing_export: {path}"}

    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).strftime("%Y-%m-%d")
    t0 = time.perf_counter()

    buckets: dict[str, dict] = defaultdict(_bucket)

    # iterparse needs `events=("end",)` so we receive each element fully
    # populated. Important: clear() after processing to release memory —
    # otherwise the parser keeps the whole tree in memory and OOMs on
    # 1.9 GB files.
    context = ET.iterparse(str(path), events=("end",))

    n_processed = 0
    n_records = 0
    n_summaries = 0
    n_workouts = 0

    for event, elem in context:
        tag = elem.tag
        if tag == "Record":
            n_records += 1
            rtype = elem.get("type")
            mapping = _RECORD_FIELDS.get(rtype)
            if mapping is None:
                elem.clear()
                continue
            agg_kind, field = mapping
            date = _parse_date(elem.get("startDate"))
            if not date or date < cutoff:
                elem.clear()
                continue
            try:
                raw = float(elem.get("value", "0"))
            except (TypeError, ValueError):
                elem.clear()
                continue
            unit = elem.get("unit") or ""
            # Distance unit normalization. The export usually uses km but
            # some workout sources emit miles.
            if field == "distance_km" and unit.lower() == "mi":
                raw *= _KM_PER_MILE

            bucket = buckets[date]
            if agg_kind == "sum":
                bucket[field] += raw
            elif agg_kind == "avg":
                bucket[field].append(raw)
            elif agg_kind == "max":
                # "max" really means "latest seen" for VO2Max / weight —
                # the export is roughly chronological so last wins.
                bucket[field] = raw
            n_processed += 1
        elif tag == "ActivitySummary":
            n_summaries += 1
            date = elem.get("dateComponents")
            if date and date >= cutoff:
                bucket = buckets[date]
                try:
                    bucket["active_kcal_summary"] = float(
                        elem.get("activeEnergyBurned") or 0
                    )
                    bucket["active_kcal_goal"] = float(
                        elem.get("activeEnergyBurnedGoal") or 0
                    )
                    bucket["exercise_min_summary"] = int(float(
                        elem.get("appleExerciseTime") or 0
                    ))
                    bucket["exercise_goal"] = int(float(
                        elem.get("appleExerciseTimeGoal") or 0
                    ))
                    bucket["stand_hours"] = int(float(
                        elem.get("appleStandHours") or 0
                    ))
                    bucket["stand_goal"] = int(float(
                        elem.get("appleStandHoursGoal") or 0
                    ))
                except (TypeError, ValueError):
                    pass
        elif tag == "Workout":
            n_workouts += 1
            date = _parse_date(elem.get("startDate"))
            if date and date >= cutoff:
                bucket = buckets[date]
                bucket["n_workouts"] += 1
                wt = elem.get("workoutActivityType") or ""
                if wt.startswith("HKWorkoutActivityType"):
                    wt = wt[len("HKWorkoutActivityType"):]
                if wt:
                    bucket["workout_types"].add(wt)
        # Always clear to keep memory bounded — even for elements we
        # didn't recognize (e.g., MetadataEntry inside Workout).
        elem.clear()

    # Finalize per-date aggregates.
    rows = []
    for date, b in sorted(buckets.items()):
        active_kcal = b.get("active_kcal_summary")
        if active_kcal is None:
            active_kcal = b["active_kcal_records"] or None
        exercise_min = b.get("exercise_min_summary")
        if exercise_min is None:
            exercise_min = b["exercise_min_records"] or None

        def _mean(xs: list[float]) -> float | None:
            return round(sum(xs) / len(xs), 2) if xs else None

        rows.append({
            "date": date,
            "steps": int(b["steps"]) if b["steps"] else None,
            "distance_km": round(b["distance_km"], 3) if b["distance_km"] else None,
            "flights_climbed": int(b["flights_climbed"]) if b["flights_climbed"] else None,
            "active_kcal": round(active_kcal, 1) if active_kcal else None,
            "active_kcal_goal": b.get("active_kcal_goal"),
            "exercise_min": exercise_min,
            "exercise_goal": b.get("exercise_goal"),
            "stand_hours": b.get("stand_hours"),
            "stand_goal": b.get("stand_goal"),
            "resting_hr": _mean(b["resting_hr"]),
            "hr_avg": _mean(b["hr_avg"]),
            "hrv_sdnn": _mean(b["hrv_sdnn"]),
            "spo2_avg": _mean(b["spo2_avg"]),
            "resp_rate": _mean(b["resp_rate"]),
            "vo2_max": b["vo2_max"],
            "body_mass_kg": b["body_mass_kg"],
            "n_workouts": b["n_workouts"] if b["n_workouts"] else None,
            "workout_types": ",".join(sorted(b["workout_types"])) if b["workout_types"] else None,
        })

    # Persist.
    _ensure_table()
    from rag import _ragvec_state_conn  # noqa: PLC0415

    now = time.time()
    cols = [
        "date", "steps", "distance_km", "flights_climbed",
        "active_kcal", "active_kcal_goal",
        "exercise_min", "exercise_goal",
        "stand_hours", "stand_goal",
        "resting_hr", "hr_avg", "hrv_sdnn",
        "spo2_avg", "resp_rate",
        "vo2_max", "body_mass_kg",
        "n_workouts", "workout_types",
        "updated_at",
    ]
    placeholders = ", ".join("?" for _ in cols)
    update_set = ", ".join(f"{c}=excluded.{c}" for c in cols if c != "date")

    with _ragvec_state_conn() as conn:
        for r in rows:
            values = tuple(r.get(c) if c != "updated_at" else now for c in cols)
            conn.execute(
                f"INSERT INTO rag_apple_health_daily ({', '.join(cols)}) "
                f"VALUES ({placeholders}) "
                f"ON CONFLICT(date) DO UPDATE SET {update_set}",
                values,
            )

    elapsed = round(time.perf_counter() - t0, 2)
    return {
        "imported": len(rows),
        "days_seen": [r["date"] for r in rows],
        "records_scanned": n_records,
        "summaries_scanned": n_summaries,
        "workouts_scanned": n_workouts,
        "records_kept": n_processed,
        "elapsed_s": elapsed,
        "export_path": str(path),
    }


# ── Read API for the web/dashboard ────────────────────────────────────────


def daily_summary(date: str) -> dict | None:
    """Single-day row from `rag_apple_health_daily`. Returns None if not
    found. `date` must be `YYYY-MM-DD` local.
    """
    _ensure_table()
    from rag import _ragvec_state_conn  # noqa: PLC0415

    try:
        with _ragvec_state_conn() as conn:
            cur = conn.execute(
                "SELECT * FROM rag_apple_health_daily WHERE date=?", (date,)
            )
            cols = [c[0] for c in cur.description]
            row = cur.fetchone()
    except Exception:
        return None
    if row is None:
        return None
    return dict(zip(cols, row))


def recent_summaries(days: int = 14) -> list[dict]:
    """Most recent `days` rows (oldest → newest order) for sparklines.
    Empty list when the table doesn't exist or is empty.
    """
    _ensure_table()
    from rag import _ragvec_state_conn  # noqa: PLC0415

    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).strftime("%Y-%m-%d")
    try:
        with _ragvec_state_conn() as conn:
            cur = conn.execute(
                "SELECT * FROM rag_apple_health_daily WHERE date >= ? "
                "ORDER BY date ASC",
                (cutoff,),
            )
            cols = [c[0] for c in cur.description]
            rows = cur.fetchall()
    except Exception:
        return []
    return [dict(zip(cols, r)) for r in rows]
